name: KeiiCore
version: '${project.version}'
main: dev.keii.gatekeeper.gatekeeper
api-version: '1.20'

commands:
  invite:
    description: Invite a player to the server
    usage: /invite <Minecraft Username>
    permission: keii.gatekeeper.invite